// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/tunnel.proto

package com.yumcouver.tunnel.server.protobuf;

public final class TunnelProto {
  private TunnelProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TunnelCommandOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TunnelCommand)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .TunnelCommand.Method method = 1;</code>
     */
    boolean hasMethod();
    /**
     * <code>required .TunnelCommand.Method method = 1;</code>
     */
    com.yumcouver.tunnel.server.protobuf.TunnelProto.TunnelCommand.Method getMethod();

    /**
     * <code>required .TunnelCommand.EndType sourceType = 2;</code>
     */
    boolean hasSourceType();
    /**
     * <code>required .TunnelCommand.EndType sourceType = 2;</code>
     */
    com.yumcouver.tunnel.server.protobuf.TunnelProto.TunnelCommand.EndType getSourceType();

    /**
     * <code>required .TunnelCommand.EndType destinationType = 3;</code>
     */
    boolean hasDestinationType();
    /**
     * <code>required .TunnelCommand.EndType destinationType = 3;</code>
     */
    com.yumcouver.tunnel.server.protobuf.TunnelProto.TunnelCommand.EndType getDestinationType();

    /**
     * <code>optional string sourceId = 4;</code>
     */
    boolean hasSourceId();
    /**
     * <code>optional string sourceId = 4;</code>
     */
    java.lang.String getSourceId();
    /**
     * <code>optional string sourceId = 4;</code>
     */
    com.google.protobuf.ByteString
        getSourceIdBytes();

    /**
     * <code>optional string destinationId = 5;</code>
     */
    boolean hasDestinationId();
    /**
     * <code>optional string destinationId = 5;</code>
     */
    java.lang.String getDestinationId();
    /**
     * <code>optional string destinationId = 5;</code>
     */
    com.google.protobuf.ByteString
        getDestinationIdBytes();

    /**
     * <code>optional uint32 sourcePort = 6;</code>
     */
    boolean hasSourcePort();
    /**
     * <code>optional uint32 sourcePort = 6;</code>
     */
    int getSourcePort();

    /**
     * <code>optional uint32 destinationPort = 7;</code>
     */
    boolean hasDestinationPort();
    /**
     * <code>optional uint32 destinationPort = 7;</code>
     */
    int getDestinationPort();

    /**
     * <code>optional bytes message = 8;</code>
     */
    boolean hasMessage();
    /**
     * <code>optional bytes message = 8;</code>
     */
    com.google.protobuf.ByteString getMessage();
  }
  /**
   * Protobuf type {@code TunnelCommand}
   */
  public static final class TunnelCommand extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:TunnelCommand)
      TunnelCommandOrBuilder {
    // Use TunnelCommand.newBuilder() to construct.
    private TunnelCommand(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TunnelCommand(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TunnelCommand defaultInstance;
    public static TunnelCommand getDefaultInstance() {
      return defaultInstance;
    }

    public TunnelCommand getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TunnelCommand(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.yumcouver.tunnel.server.protobuf.TunnelProto.TunnelCommand.Method value = com.yumcouver.tunnel.server.protobuf.TunnelProto.TunnelCommand.Method.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                method_ = value;
              }
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.yumcouver.tunnel.server.protobuf.TunnelProto.TunnelCommand.EndType value = com.yumcouver.tunnel.server.protobuf.TunnelProto.TunnelCommand.EndType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                sourceType_ = value;
              }
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              com.yumcouver.tunnel.server.protobuf.TunnelProto.TunnelCommand.EndType value = com.yumcouver.tunnel.server.protobuf.TunnelProto.TunnelCommand.EndType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                destinationType_ = value;
              }
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              sourceId_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              destinationId_ = bs;
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              sourcePort_ = input.readUInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              destinationPort_ = input.readUInt32();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              message_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yumcouver.tunnel.server.protobuf.TunnelProto.internal_static_TunnelCommand_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yumcouver.tunnel.server.protobuf.TunnelProto.internal_static_TunnelCommand_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yumcouver.tunnel.server.protobuf.TunnelProto.TunnelCommand.class, com.yumcouver.tunnel.server.protobuf.TunnelProto.TunnelCommand.Builder.class);
    }

    public static com.google.protobuf.Parser<TunnelCommand> PARSER =
        new com.google.protobuf.AbstractParser<TunnelCommand>() {
      public TunnelCommand parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TunnelCommand(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TunnelCommand> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code TunnelCommand.Method}
     */
    public enum Method
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>ACK = 0;</code>
       */
      ACK(0, 0),
      /**
       * <code>SEND = 1;</code>
       */
      SEND(1, 1),
      /**
       * <code>ID = 2;</code>
       */
      ID(2, 2),
      /**
       * <code>ERROR = 3;</code>
       */
      ERROR(3, 3),
      ;

      /**
       * <code>ACK = 0;</code>
       */
      public static final int ACK_VALUE = 0;
      /**
       * <code>SEND = 1;</code>
       */
      public static final int SEND_VALUE = 1;
      /**
       * <code>ID = 2;</code>
       */
      public static final int ID_VALUE = 2;
      /**
       * <code>ERROR = 3;</code>
       */
      public static final int ERROR_VALUE = 3;


      public final int getNumber() { return value; }

      public static Method valueOf(int value) {
        switch (value) {
          case 0: return ACK;
          case 1: return SEND;
          case 2: return ID;
          case 3: return ERROR;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Method>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Method>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Method>() {
              public Method findValueByNumber(int number) {
                return Method.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.yumcouver.tunnel.server.protobuf.TunnelProto.TunnelCommand.getDescriptor().getEnumTypes().get(0);
      }

      private static final Method[] VALUES = values();

      public static Method valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Method(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:TunnelCommand.Method)
    }

    /**
     * Protobuf enum {@code TunnelCommand.EndType}
     */
    public enum EndType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>SERVER = 0;</code>
       */
      SERVER(0, 0),
      /**
       * <code>CLIENT = 1;</code>
       */
      CLIENT(1, 1),
      ;

      /**
       * <code>SERVER = 0;</code>
       */
      public static final int SERVER_VALUE = 0;
      /**
       * <code>CLIENT = 1;</code>
       */
      public static final int CLIENT_VALUE = 1;


      public final int getNumber() { return value; }

      public static EndType valueOf(int value) {
        switch (value) {
          case 0: return SERVER;
          case 1: return CLIENT;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<EndType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<EndType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<EndType>() {
              public EndType findValueByNumber(int number) {
                return EndType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.yumcouver.tunnel.server.protobuf.TunnelProto.TunnelCommand.getDescriptor().getEnumTypes().get(1);
      }

      private static final EndType[] VALUES = values();

      public static EndType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private EndType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:TunnelCommand.EndType)
    }

    private int bitField0_;
    public static final int METHOD_FIELD_NUMBER = 1;
    private com.yumcouver.tunnel.server.protobuf.TunnelProto.TunnelCommand.Method method_;
    /**
     * <code>required .TunnelCommand.Method method = 1;</code>
     */
    public boolean hasMethod() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .TunnelCommand.Method method = 1;</code>
     */
    public com.yumcouver.tunnel.server.protobuf.TunnelProto.TunnelCommand.Method getMethod() {
      return method_;
    }

    public static final int SOURCETYPE_FIELD_NUMBER = 2;
    private com.yumcouver.tunnel.server.protobuf.TunnelProto.TunnelCommand.EndType sourceType_;
    /**
     * <code>required .TunnelCommand.EndType sourceType = 2;</code>
     */
    public boolean hasSourceType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .TunnelCommand.EndType sourceType = 2;</code>
     */
    public com.yumcouver.tunnel.server.protobuf.TunnelProto.TunnelCommand.EndType getSourceType() {
      return sourceType_;
    }

    public static final int DESTINATIONTYPE_FIELD_NUMBER = 3;
    private com.yumcouver.tunnel.server.protobuf.TunnelProto.TunnelCommand.EndType destinationType_;
    /**
     * <code>required .TunnelCommand.EndType destinationType = 3;</code>
     */
    public boolean hasDestinationType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required .TunnelCommand.EndType destinationType = 3;</code>
     */
    public com.yumcouver.tunnel.server.protobuf.TunnelProto.TunnelCommand.EndType getDestinationType() {
      return destinationType_;
    }

    public static final int SOURCEID_FIELD_NUMBER = 4;
    private java.lang.Object sourceId_;
    /**
     * <code>optional string sourceId = 4;</code>
     */
    public boolean hasSourceId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string sourceId = 4;</code>
     */
    public java.lang.String getSourceId() {
      java.lang.Object ref = sourceId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sourceId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string sourceId = 4;</code>
     */
    public com.google.protobuf.ByteString
        getSourceIdBytes() {
      java.lang.Object ref = sourceId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sourceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESTINATIONID_FIELD_NUMBER = 5;
    private java.lang.Object destinationId_;
    /**
     * <code>optional string destinationId = 5;</code>
     */
    public boolean hasDestinationId() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string destinationId = 5;</code>
     */
    public java.lang.String getDestinationId() {
      java.lang.Object ref = destinationId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          destinationId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string destinationId = 5;</code>
     */
    public com.google.protobuf.ByteString
        getDestinationIdBytes() {
      java.lang.Object ref = destinationId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        destinationId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SOURCEPORT_FIELD_NUMBER = 6;
    private int sourcePort_;
    /**
     * <code>optional uint32 sourcePort = 6;</code>
     */
    public boolean hasSourcePort() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional uint32 sourcePort = 6;</code>
     */
    public int getSourcePort() {
      return sourcePort_;
    }

    public static final int DESTINATIONPORT_FIELD_NUMBER = 7;
    private int destinationPort_;
    /**
     * <code>optional uint32 destinationPort = 7;</code>
     */
    public boolean hasDestinationPort() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional uint32 destinationPort = 7;</code>
     */
    public int getDestinationPort() {
      return destinationPort_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 8;
    private com.google.protobuf.ByteString message_;
    /**
     * <code>optional bytes message = 8;</code>
     */
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional bytes message = 8;</code>
     */
    public com.google.protobuf.ByteString getMessage() {
      return message_;
    }

    private void initFields() {
      method_ = com.yumcouver.tunnel.server.protobuf.TunnelProto.TunnelCommand.Method.ACK;
      sourceType_ = com.yumcouver.tunnel.server.protobuf.TunnelProto.TunnelCommand.EndType.SERVER;
      destinationType_ = com.yumcouver.tunnel.server.protobuf.TunnelProto.TunnelCommand.EndType.SERVER;
      sourceId_ = "";
      destinationId_ = "";
      sourcePort_ = 0;
      destinationPort_ = 0;
      message_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMethod()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSourceType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDestinationType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, method_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, sourceType_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, destinationType_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getSourceIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getDestinationIdBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeUInt32(6, sourcePort_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeUInt32(7, destinationPort_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, message_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, method_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, sourceType_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, destinationType_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getSourceIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getDestinationIdBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, sourcePort_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(7, destinationPort_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, message_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.yumcouver.tunnel.server.protobuf.TunnelProto.TunnelCommand parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yumcouver.tunnel.server.protobuf.TunnelProto.TunnelCommand parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yumcouver.tunnel.server.protobuf.TunnelProto.TunnelCommand parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yumcouver.tunnel.server.protobuf.TunnelProto.TunnelCommand parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yumcouver.tunnel.server.protobuf.TunnelProto.TunnelCommand parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.yumcouver.tunnel.server.protobuf.TunnelProto.TunnelCommand parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.yumcouver.tunnel.server.protobuf.TunnelProto.TunnelCommand parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.yumcouver.tunnel.server.protobuf.TunnelProto.TunnelCommand parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.yumcouver.tunnel.server.protobuf.TunnelProto.TunnelCommand parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.yumcouver.tunnel.server.protobuf.TunnelProto.TunnelCommand parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.yumcouver.tunnel.server.protobuf.TunnelProto.TunnelCommand prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TunnelCommand}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TunnelCommand)
        com.yumcouver.tunnel.server.protobuf.TunnelProto.TunnelCommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yumcouver.tunnel.server.protobuf.TunnelProto.internal_static_TunnelCommand_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yumcouver.tunnel.server.protobuf.TunnelProto.internal_static_TunnelCommand_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yumcouver.tunnel.server.protobuf.TunnelProto.TunnelCommand.class, com.yumcouver.tunnel.server.protobuf.TunnelProto.TunnelCommand.Builder.class);
      }

      // Construct using com.yumcouver.tunnel.server.protobuf.TunnelProto.TunnelCommand.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        method_ = com.yumcouver.tunnel.server.protobuf.TunnelProto.TunnelCommand.Method.ACK;
        bitField0_ = (bitField0_ & ~0x00000001);
        sourceType_ = com.yumcouver.tunnel.server.protobuf.TunnelProto.TunnelCommand.EndType.SERVER;
        bitField0_ = (bitField0_ & ~0x00000002);
        destinationType_ = com.yumcouver.tunnel.server.protobuf.TunnelProto.TunnelCommand.EndType.SERVER;
        bitField0_ = (bitField0_ & ~0x00000004);
        sourceId_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        destinationId_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        sourcePort_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        destinationPort_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        message_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yumcouver.tunnel.server.protobuf.TunnelProto.internal_static_TunnelCommand_descriptor;
      }

      public com.yumcouver.tunnel.server.protobuf.TunnelProto.TunnelCommand getDefaultInstanceForType() {
        return com.yumcouver.tunnel.server.protobuf.TunnelProto.TunnelCommand.getDefaultInstance();
      }

      public com.yumcouver.tunnel.server.protobuf.TunnelProto.TunnelCommand build() {
        com.yumcouver.tunnel.server.protobuf.TunnelProto.TunnelCommand result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.yumcouver.tunnel.server.protobuf.TunnelProto.TunnelCommand buildPartial() {
        com.yumcouver.tunnel.server.protobuf.TunnelProto.TunnelCommand result = new com.yumcouver.tunnel.server.protobuf.TunnelProto.TunnelCommand(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.method_ = method_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sourceType_ = sourceType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.destinationType_ = destinationType_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.sourceId_ = sourceId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.destinationId_ = destinationId_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.sourcePort_ = sourcePort_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.destinationPort_ = destinationPort_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.message_ = message_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yumcouver.tunnel.server.protobuf.TunnelProto.TunnelCommand) {
          return mergeFrom((com.yumcouver.tunnel.server.protobuf.TunnelProto.TunnelCommand)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yumcouver.tunnel.server.protobuf.TunnelProto.TunnelCommand other) {
        if (other == com.yumcouver.tunnel.server.protobuf.TunnelProto.TunnelCommand.getDefaultInstance()) return this;
        if (other.hasMethod()) {
          setMethod(other.getMethod());
        }
        if (other.hasSourceType()) {
          setSourceType(other.getSourceType());
        }
        if (other.hasDestinationType()) {
          setDestinationType(other.getDestinationType());
        }
        if (other.hasSourceId()) {
          bitField0_ |= 0x00000008;
          sourceId_ = other.sourceId_;
          onChanged();
        }
        if (other.hasDestinationId()) {
          bitField0_ |= 0x00000010;
          destinationId_ = other.destinationId_;
          onChanged();
        }
        if (other.hasSourcePort()) {
          setSourcePort(other.getSourcePort());
        }
        if (other.hasDestinationPort()) {
          setDestinationPort(other.getDestinationPort());
        }
        if (other.hasMessage()) {
          setMessage(other.getMessage());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMethod()) {
          
          return false;
        }
        if (!hasSourceType()) {
          
          return false;
        }
        if (!hasDestinationType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yumcouver.tunnel.server.protobuf.TunnelProto.TunnelCommand parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yumcouver.tunnel.server.protobuf.TunnelProto.TunnelCommand) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.yumcouver.tunnel.server.protobuf.TunnelProto.TunnelCommand.Method method_ = com.yumcouver.tunnel.server.protobuf.TunnelProto.TunnelCommand.Method.ACK;
      /**
       * <code>required .TunnelCommand.Method method = 1;</code>
       */
      public boolean hasMethod() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .TunnelCommand.Method method = 1;</code>
       */
      public com.yumcouver.tunnel.server.protobuf.TunnelProto.TunnelCommand.Method getMethod() {
        return method_;
      }
      /**
       * <code>required .TunnelCommand.Method method = 1;</code>
       */
      public Builder setMethod(com.yumcouver.tunnel.server.protobuf.TunnelProto.TunnelCommand.Method value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        method_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .TunnelCommand.Method method = 1;</code>
       */
      public Builder clearMethod() {
        bitField0_ = (bitField0_ & ~0x00000001);
        method_ = com.yumcouver.tunnel.server.protobuf.TunnelProto.TunnelCommand.Method.ACK;
        onChanged();
        return this;
      }

      private com.yumcouver.tunnel.server.protobuf.TunnelProto.TunnelCommand.EndType sourceType_ = com.yumcouver.tunnel.server.protobuf.TunnelProto.TunnelCommand.EndType.SERVER;
      /**
       * <code>required .TunnelCommand.EndType sourceType = 2;</code>
       */
      public boolean hasSourceType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .TunnelCommand.EndType sourceType = 2;</code>
       */
      public com.yumcouver.tunnel.server.protobuf.TunnelProto.TunnelCommand.EndType getSourceType() {
        return sourceType_;
      }
      /**
       * <code>required .TunnelCommand.EndType sourceType = 2;</code>
       */
      public Builder setSourceType(com.yumcouver.tunnel.server.protobuf.TunnelProto.TunnelCommand.EndType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        sourceType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .TunnelCommand.EndType sourceType = 2;</code>
       */
      public Builder clearSourceType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sourceType_ = com.yumcouver.tunnel.server.protobuf.TunnelProto.TunnelCommand.EndType.SERVER;
        onChanged();
        return this;
      }

      private com.yumcouver.tunnel.server.protobuf.TunnelProto.TunnelCommand.EndType destinationType_ = com.yumcouver.tunnel.server.protobuf.TunnelProto.TunnelCommand.EndType.SERVER;
      /**
       * <code>required .TunnelCommand.EndType destinationType = 3;</code>
       */
      public boolean hasDestinationType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required .TunnelCommand.EndType destinationType = 3;</code>
       */
      public com.yumcouver.tunnel.server.protobuf.TunnelProto.TunnelCommand.EndType getDestinationType() {
        return destinationType_;
      }
      /**
       * <code>required .TunnelCommand.EndType destinationType = 3;</code>
       */
      public Builder setDestinationType(com.yumcouver.tunnel.server.protobuf.TunnelProto.TunnelCommand.EndType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        destinationType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .TunnelCommand.EndType destinationType = 3;</code>
       */
      public Builder clearDestinationType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        destinationType_ = com.yumcouver.tunnel.server.protobuf.TunnelProto.TunnelCommand.EndType.SERVER;
        onChanged();
        return this;
      }

      private java.lang.Object sourceId_ = "";
      /**
       * <code>optional string sourceId = 4;</code>
       */
      public boolean hasSourceId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string sourceId = 4;</code>
       */
      public java.lang.String getSourceId() {
        java.lang.Object ref = sourceId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sourceId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string sourceId = 4;</code>
       */
      public com.google.protobuf.ByteString
          getSourceIdBytes() {
        java.lang.Object ref = sourceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sourceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string sourceId = 4;</code>
       */
      public Builder setSourceId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        sourceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string sourceId = 4;</code>
       */
      public Builder clearSourceId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        sourceId_ = getDefaultInstance().getSourceId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string sourceId = 4;</code>
       */
      public Builder setSourceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        sourceId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object destinationId_ = "";
      /**
       * <code>optional string destinationId = 5;</code>
       */
      public boolean hasDestinationId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string destinationId = 5;</code>
       */
      public java.lang.String getDestinationId() {
        java.lang.Object ref = destinationId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            destinationId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string destinationId = 5;</code>
       */
      public com.google.protobuf.ByteString
          getDestinationIdBytes() {
        java.lang.Object ref = destinationId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          destinationId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string destinationId = 5;</code>
       */
      public Builder setDestinationId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        destinationId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string destinationId = 5;</code>
       */
      public Builder clearDestinationId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        destinationId_ = getDefaultInstance().getDestinationId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string destinationId = 5;</code>
       */
      public Builder setDestinationIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        destinationId_ = value;
        onChanged();
        return this;
      }

      private int sourcePort_ ;
      /**
       * <code>optional uint32 sourcePort = 6;</code>
       */
      public boolean hasSourcePort() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional uint32 sourcePort = 6;</code>
       */
      public int getSourcePort() {
        return sourcePort_;
      }
      /**
       * <code>optional uint32 sourcePort = 6;</code>
       */
      public Builder setSourcePort(int value) {
        bitField0_ |= 0x00000020;
        sourcePort_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 sourcePort = 6;</code>
       */
      public Builder clearSourcePort() {
        bitField0_ = (bitField0_ & ~0x00000020);
        sourcePort_ = 0;
        onChanged();
        return this;
      }

      private int destinationPort_ ;
      /**
       * <code>optional uint32 destinationPort = 7;</code>
       */
      public boolean hasDestinationPort() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional uint32 destinationPort = 7;</code>
       */
      public int getDestinationPort() {
        return destinationPort_;
      }
      /**
       * <code>optional uint32 destinationPort = 7;</code>
       */
      public Builder setDestinationPort(int value) {
        bitField0_ |= 0x00000040;
        destinationPort_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 destinationPort = 7;</code>
       */
      public Builder clearDestinationPort() {
        bitField0_ = (bitField0_ & ~0x00000040);
        destinationPort_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString message_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes message = 8;</code>
       */
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional bytes message = 8;</code>
       */
      public com.google.protobuf.ByteString getMessage() {
        return message_;
      }
      /**
       * <code>optional bytes message = 8;</code>
       */
      public Builder setMessage(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes message = 8;</code>
       */
      public Builder clearMessage() {
        bitField0_ = (bitField0_ & ~0x00000080);
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:TunnelCommand)
    }

    static {
      defaultInstance = new TunnelCommand(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:TunnelCommand)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TunnelCommand_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_TunnelCommand_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032src/main/java/tunnel.proto\"\315\002\n\rTunnelC" +
      "ommand\022%\n\006method\030\001 \002(\0162\025.TunnelCommand.M" +
      "ethod\022*\n\nsourceType\030\002 \002(\0162\026.TunnelComman" +
      "d.EndType\022/\n\017destinationType\030\003 \002(\0162\026.Tun" +
      "nelCommand.EndType\022\020\n\010sourceId\030\004 \001(\t\022\025\n\r" +
      "destinationId\030\005 \001(\t\022\022\n\nsourcePort\030\006 \001(\r\022" +
      "\027\n\017destinationPort\030\007 \001(\r\022\017\n\007message\030\010 \001(" +
      "\014\".\n\006Method\022\007\n\003ACK\020\000\022\010\n\004SEND\020\001\022\006\n\002ID\020\002\022\t" +
      "\n\005ERROR\020\003\"!\n\007EndType\022\n\n\006SERVER\020\000\022\n\n\006CLIE" +
      "NT\020\001B5\n$com.yumcouver.tunnel.server.prot",
      "obufB\013TunnelProtoH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_TunnelCommand_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TunnelCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_TunnelCommand_descriptor,
        new java.lang.String[] { "Method", "SourceType", "DestinationType", "SourceId", "DestinationId", "SourcePort", "DestinationPort", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
